name: pokemon
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^4.0.1
  graphql_flutter: ^5.1.2

dev_dependencies:
  artemis: ^7.11.0-beta.1 # Artemis is only used for the generation, so it isn't needed run-time
  build_runner: ^2.3.3 # Used with Artemis for generating Dart type files

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0 # Used with Artemis for parsing new types

flutter:
  uses-material-design: true
